name: Nix

on:
  push:
    branches: [main]

jobs:
  nix:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc:
          - "8.8.4"
          - "8.10.4"
        exclude:
          - os: macOS-latest
            ghc: 8.8.4
          - os: windows-latest
            ghc: 8.8.4

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set nix path
        id: nix-path
        run: |
          echo ::set-output name=nixpkgs::$(jq -r .nixpkgs.url ./nix/sources.json)
      
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=${{ steps.nix-path.outputs.nixpkgs }}
          extra_nix_config: |
            log-lines = 1000

      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: stan
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: |
          nix-build ./nix/release.nix --argstr compiler ${{ matrix.ghc }}
